# vi docker-compose.yml
version: '3.3'
services:
    mongo:
        image: mongo
        ports:
            - '27017:27017'
        container_name: ChatApp-MongoDB
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        env_file:
            -   .env

    mongo-express:
        image: mongo-express
        ports:
            - '8081:8081'
        container_name: ChatApp-MongoDB-Express
        restart: unless-stopped
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - ME_CONFIG_MONGODB_SERVER=mongo
        depends_on:
            - mongo
        env_file:
            -   .env
