# vi docker-compose.yml
version: '3.3'
services:
    mongo:
        image: mongo
        ports:
            - '27017:27017'
        container_name: ChatApp-MongoDB
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        env_file:
            -   .env


